config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # # all lists
  # get 'lists', to: 'lists#index'

  # # create new list
  # get 'lists/new', to: 'lists#new'
  # post 'lists', to: 'lists#create'

  # # show a list
  # get 'lists/:id', to: 'lists#show'

  # resources :movies
  root to: 'lists#index'

  resources :lists, only: %i[index new create show] do
    resources :bookmarks, only: %i[new create]
  end
  resources :bookmarks, only: %i[destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, length: { minimum: 6 }
  validates :movie, uniqueness: { scope: :list }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks
  has_many :movies, through: :bookmarks, dependent: :destroy
  validates :name, uniqueness: true, presence: true
  has_one_attached :photo
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, :overview, uniqueness: true, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_bookmark, only: :destroy
  before_action :set_list, only: %i[new create]
  def index
    @bookmarks = Bookmark.all
  end

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @bookmark.destroy
    redirect_to list_path(@bookmark.list), status: :see_other
  end

  private

  def set_bookmark
    @bookmark = Bookmark.find(params[:id])
  end

  def set_list
    @list = List.find(params[:list_id])
  end

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: %i[show]
  def index
    @lists = List.all
  end

  def show
    @bookmark = Bookmark.new
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name, :photo)
  end

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/_bookmark.html.erb
<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.input :comment, label: "Comment" %>
  <%= f.association :movie %>
  <%= f.submit "Save", class: "btn btn-primary" %>
<% end %>

app/views/bookmarks/new.html.erb
<h3 class='text-center mt-3'>Create a new bookmark</h3>

<%= render 'bookmark', bookmark: @bookmark %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/lists/_list_form.html.erb
<%= simple_form_for @list do |f| %>
  <%= f.input :name, label: "Name" %>
  <%= f.input :photo, as: :file %>
  <%= f.submit "Save", class: "btn btn-primary" %>
<% end %>

app/views/lists/index.html.erb
  <h1 class="text-center mt-3 mb-5">Our lists</h1>

<div class="row">
<% @lists.each do |list| %>
  <div class="col-md-4">
    <div class="card mb-3">
      <div class="card-body">
        <h5 class="card-title"><%= link_to list.name, list_path(list) %> </h5>
      </div><%# card body %>
    </div>
  </div>
<% end %>
</div>


  <h3><%= link_to "New list", new_list_path, class: "btn btn-primary mt-2" %></h3>

<%= cl_image_tag("upidyuj8zq52aqyq1p9v",
      width: 400, height: 300, crop: :fill) %>

<!-- for face detection -->
<%= cl_image_tag("psr3omslu2oikuwcoib1",
      width: 150, height: 150, crop: :thumb, gravity: :face) %>

app/views/lists/new.html.erb
<h3 class='text-center mt-3'>Create a new list</h3>

<%= render 'list_form', list: @list %>

app/views/lists/show.html.erb
<%= link_to "Back to all lists", lists_path, class: "btn btn-secondary mt-3" %>
<h3 class='text-center m-3'>List details</h3>
<div class="card">
  <div class="card-body">
    <h5 class="card-title"><%= @list.name %></h5>
    <%= cl_image_tag @list.photo.key, height: 300, width: 400, crop: :fill %>
    <p class="card-text">
Lorem ipsum, dolor sit amet consectetur adipisicing elit. Adipisci iusto debitis dolor. Expedita nulla modi a totam. Laudantium eos ratione aut consequuntur magnam voluptatum excepturi reiciendis delectus nemo, in voluptatem.
    </p>
      <div class="card mb-3">
        <div class="card-body">
        <h5 class="card-title">Bookmarks List</h5>
        <ul>
        <% @list.bookmarks.each do |bookmark| %>
          <li><%= bookmark.movie.title %> -- <%= bookmark.comment %> -- <%= link_to "Delete", bookmark_path(bookmark), method: :delete, data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "link-danger mt-2" %></li>
        <% end %>
        </ul>
        </div>
      </div>
  </div>
</div>

<div class="card-category"
  style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path @list.photo.key, height: 300, crop: :fill %>')">
  Cool article
</div>

<h3 class='text-center mt-2'>Create a new bookmark</h3>

<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.input :comment, label: "Comment", placeholder: 'Enter a comment about the movie' %>
  <%= f.association :movie %>
  <%= f.submit "Save", class: "btn btn-primary" %>
<% end %>

<hr>

app/views/movies/index.html.erb
<h1 class="text-center mt-3 mb-5">All Movies</h1>
<div class="row">
<% @movies.each do |movie| %>
<div class="col-md-4">
<div class="card mb-3">
  <div class="card-body">
    <h5 class="card-title"><%= movie.title %></h5>
    <hr>
    <p class="card-text">
      <strong>Description:</strong> <%= movie.overview %>
    </p>
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        <strong>Price per night:</strong> <%= movie.rating %>
      </li>
      <li class="list-group-item">
        <%= link_to "More info", movie_path(movie), class: "link-primary mt-2" %>
        <%= link_to "Edit", edit_movie_path(movie), class: "link-warning mt-2" %>
        <%= link_to "Delete", movie_path(movie), method: :delete, data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "link-danger mt-2" %>
      </li>
    </ul>
  </div>
</div>
</div>
<% end %>
</div>